# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: Android App
        scripts:
            - ./gradlew build
            - name: Set up key.properties
              script: |
                echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
                cat >> "$FCI_BUILD_DIR/project_directory/android/key.properties" <<EOF
                storePassword=$FCI_KEYSTORE_PASSWORD
                keyPassword=$FCI_KEY_PASSWORD
                keyAlias=$FCI_KEY_ALIAS
                storeFile=/tmp/keystore.keystore
                EOF    
        artifacts:
            - app/build/outputs/**/*.apk
        environment:
            vars:
                FCI_KEYSTORE: Encrypted(Z0FBQUFBQmZ0UlpZZUlRX3BfaV9QRUVBdENQRERMVG5wbFlzSGlMU0pfREZIR2prMEs4UGNTR2QtdU1lVnBDR0xjQ25sLVRtOW9GM20xRVNzbmRhVzUtVUdkOGFFM29vLUE9PQ==) # PUT THE ENCRYPTED KEYSTORE FILE HERE
                FCI_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmZ0UmFkcnllbjJUbXFGMFJPbkpJSmxXSzVyZjBlX0kwMjc1eDZvRkM1eTF3Zi1FbEJ5UFN5UXdMZE53MkQ4ZFpISjY4SlEtUTVGVjZpUXlpWDJPZy1sLXR5ZUE9PQ==) # PUT THE ENCRYPTED PASSWORD FOR THE KEYSTORE FILE HERE
                FCI_KEY_PASSWORD: Encrypted(Z0FBQUFBQmZ0UmFkcnllbjJUbXFGMFJPbkpJSmxXSzVyZjBlX0kwMjc1eDZvRkM1eTF3Zi1FbEJ5UFN5UXdMZE53MkQ4ZFpISjY4SlEtUTVGVjZpUXlpWDJPZy1sLXR5ZUE9PQ==) # PUT THE ENCRYPTED KEYSTORE ALIAS PASSWORD HERE
                FCI_KEY_ALIAS: Encrypted(Z0FBQUFBQmZ0UlpZZUlRX3BfaV9QRUVBdENQRERMVG5wbFlzSGlMU0pfREZIR2prMEs4UGNTR2QtdU1lVnBDR0xjQ25sLVRtOW9GM20xRVNzbmRhVzUtVUdkOGFFM29vLUE9PQ==) #PUT THE ENCRYPTED KEYSTORE USERNAME HERE
            ndk: r21d 
